version = 1

exclude_patterns = [
    "vendor/**",
    "examples/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/buger/goreplay"]
  dependencies_vendored = true